Algoritmo "entrada e saída de dados"
// Descrição   : entrada e saída de dados
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/04/2020
Var
// Seção de Declarações das variáveis 

   nome: caracter
   idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval ("Digite o seu nome:")
   leia(nome)
   escreval ("Digite a sua idade:")
   leia(idade)

   escreval(" o nome digitado foi:", nome)
   escreval(" a idade digitada foi:", idade)

Fimalgoritmo